version: "3.1"
services:
  nodepdffill:
    image: hassiodev/nodepdffill
    build:
      context: nodepdffill
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
  gopdftk:
    image: hassiodev/gopdftk
    build:
      context: gopdftk
      dockerfile: ./Dockerfile
    ports:
      - "3002:3000"
  nodepdfwrite:
    image: hassiodev/nodepdfwrite
    build:
      context: nodepdfwrite
      dockerfile: ./Dockerfile
    ports:
      - "3003:3000"
  orchestrator:
    image: hassiodev/orchestrator
    build:
      context: orchestrator
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "nodepdffill"
      - "gopdftk"
      - "nodepdfwrite"